version: 2
jobs:
  build:
    working_directory: ~/amqp-java-client-tests
    docker:
      - image: docker:17.06.0-git
        environment:
          BROKER_VERSION: "1.38"
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install dependencies
          command: apk add --update --upgrade curl libcurl
      - run:
          name: Build Docker image
          command: docker build -t scholzj/java-client-tests:devel .
      - deploy:
          name: Tag docker images
          command: |
            docker tag scholzj/java-client-tests:devel docker.io/scholzj/java-client-tests:devel
            docker tag scholzj/java-client-tests:devel docker.io/scholzj/java-client-tests:${BROKER_VERSION}
      - deploy:
          name: Login to Docker Hub
          command: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - deploy:
          name: Push docker images
          command: |
            docker push scholzj/java-client-tests:devel
            docker push scholzj/java-client-tests:${BROKER_VERSION}
      - deploy:
          name: Trigger tests
          command: |
            curl -u ${CIRCLECI_TOKEN}: \
              -d build_parameters[CIRCLE_JOB]=qpid_${BROKER_VERSION} \
              https://circleci.com/api/v1.1/project/github/scholzj/amqp-java-client-tests/tree/master
